import type { Criterion } from "../types.ts";

/** #10 Single criterion → Markdown (for docs, Confluence, issues). */
export function criterionToMarkdown(c: Criterion): string {
  const lines: string[] = [];
  lines.push(`## ${c.id} ${c.title} (Level ${c.level})`);
  lines.push("");
  lines.push(c.plainEnglish);
  lines.push("");
  lines.push(`**Why it matters:** ${c.whyItMatters}`);
  lines.push(`**Quick check:** ${c.quickCheck}`);
  if (c.commonMistakes.length) {
    lines.push("");
    lines.push("**Common mistakes:**");
    for (const m of c.commonMistakes) lines.push(`- ${m}`);
  }
  if (c.axeRules.length) {
    lines.push("");
    lines.push(`**axe-core rules:** ${c.axeRules.map((r) => `\`${r.ruleId}\``).join(", ")}`);
  }
  lines.push("");
  lines.push(`[Understanding ${c.id} on W3C](${c.url})`);
  return lines.join("\n");
}

/** #9 Selected criteria → a Markdown accessibility checklist. */
export function checklistToMarkdown(criteria: Criterion[], project: string): string {
  const title = project.trim() ? `${project.trim()} — Accessibility checklist` : "Accessibility checklist";
  const lines: string[] = [`# ${title}`, "", `${criteria.length} WCAG 2.2 criteria to verify.`, ""];
  const byPrinciple = new Map<string, Criterion[]>();
  for (const c of criteria) {
    const key = `${c.principle.id}. ${c.principle.name}`;
    if (!byPrinciple.has(key)) byPrinciple.set(key, []);
    byPrinciple.get(key)!.push(c);
  }
  for (const [principle, list] of [...byPrinciple.entries()].sort()) {
    lines.push(`## ${principle}`);
    for (const c of list.sort((a, b) => a.id.localeCompare(b.id))) {
      lines.push(`- [ ] **${c.id} ${c.title}** (${c.level}) — ${c.quickCheck}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

/** #9 Selected criteria → a PR-review template. */
export function checklistToPrTemplate(criteria: Criterion[], project: string): string {
  const head = project.trim() ? `### Accessibility review — ${project.trim()}` : "### Accessibility review";
  const lines: string[] = [
    head,
    "",
    "Confirm this change does not regress the following WCAG 2.2 criteria:",
    "",
  ];
  for (const c of criteria.sort((a, b) => a.id.localeCompare(b.id))) {
    lines.push(`- [ ] \`${c.id}\` ${c.title} — ${c.quickCheck}`);
  }
  lines.push("");
  lines.push("<sub>Generated by wcag-explainer</sub>");
  return lines.join("\n");
}
